// Generated by scripts/gen_design_tokens.py from design/tokens.json. Do not edit.
package dev.wavr.core.nativeui

import androidx.compose.ui.graphics.Color

object WavrTokens {
    val background = Color(0xFF0B0E12)
    val stage = Color(0xFF070A0D)
    val surface = Color(0xFF141920)
    val surfaceInset = Color(0xFF10151B)
    val elevated = Color(0xFF1C232C)
    val elevated2 = Color(0xFF232B35)
    val line = Color(0x12FFFFFF)
    val lineStrong = Color(0x21FFFFFF)
    val text = Color(0xFFEAECEE)
    val textDim = Color(0xFF9AA4AD)
    val textFaint = Color(0xFF7E8B95)
    val accent = Color(0xFF3DB54A)
    val info = Color(0xFF62A6DA)
    val warn = Color(0xFFE8A13A)
    val danger = Color(0xFFE8726A)
    val zone = Color(0xFF6EA8FE)
    val dim = textDim
    val healthy = Color(0xFF3DB54A)
    val starting = Color(0xFF7E8B95)
    val updating = Color(0xFF62A6DA)
    val paused = Color(0xFF9AA4AD)
    val degraded = Color(0xFFE8A13A)
    val attention = Color(0xFFE76423)
    val unavailable = Color(0xFFE8726A)
    val unknown = Color(0xFF7E8B95)
    const val SPACE_1 = 4.0f
    const val SPACE_2 = 8.0f
    const val SPACE_3 = 12.0f
    const val SPACE_4 = 16.0f
    const val SPACE_5 = 24.0f
    const val SPACE_6 = 32.0f
    const val SPACE_7 = 48.0f
    const val SPACE_8 = 64.0f
    const val RADIUS_SMALL = 8.0f
    const val RADIUS_MEDIUM = 12.0f
    const val RADIUS_PILL = 999.0f
    const val FONT_XS = 11.52f
    const val FONT_SM = 12.48f
    const val FONT_MD = 13.12f
    const val FONT_BASE = 14.4f
    const val FONT_LG = 16.0f
    const val FONT_XL = 17.6f
    const val FONT_XXL = 20.0f
    const val FONT_DISPLAY = 40.0f
    const val DURATION_FAST_MS = 120
    const val DURATION_MEDIUM_MS = 220
    const val DURATION_SLOW_MS = 420

    /** The colour of a runtime state; anything unrecognised is "unknown". */
    fun forState(state: String?): Color = when (state) {
        "healthy" -> healthy
        "starting" -> starting
        "updating" -> updating
        "paused" -> paused
        "degraded" -> degraded
        "attention" -> attention
        "unavailable" -> unavailable
        else -> unknown
    }
}
