"""Wavr's visual language as implementation-neutral tokens, and every native copy.

    python scripts/gen_design_tokens.py           # rewrite design/tokens.json + clients
    python scripts/gen_design_tokens.py --check   # exit 1 if anything is stale

Source of truth: the dashboard's `:root` custom properties in
frontend/index.html (owned by the frontend; this only reads them, through
scripts/gen_tokens.py). The MAPPING below names what each value MEANS -- a
surface, a state, a spacing step -- so design/tokens.json carries no CSS
names, and the Android, Apple and desktop clients are generated from it
instead of carrying hand-copied hex that drifts (they already disagreed about
the colour of an unknown state).

Units: sizes in px at a 16 px root (1rem = 16), which Android reads as dp and
Apple as points; durations in ms; easings as the four cubic-bezier numbers;
colours as #RRGGBB or #RRGGBBAA.
"""
from __future__ import annotations

import importlib.util
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location("gen_tokens", REPO / "scripts" / "gen_tokens.py")
_gt = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gt)

STATES = ("healthy", "starting", "updating", "paused", "degraded", "attention",
          "unavailable", "unknown")

MAPPING = {
    "color": {
        "background": "--bg", "stage": "--surface-stage", "surface": "--surface",
        "surface_inset": "--surface-inset", "elevated": "--elevated",
        "elevated_2": "--elevated-2", "line": "--line", "line_strong": "--line-strong",
        "text": "--text", "text_dim": "--dim", "text_faint": "--dim-deep",
        "accent": "--accent", "info": "--info", "warn": "--warn", "danger": "--danger",
        "zone": "--zone",
    },
    "state": {s: f"--state-{s}" for s in STATES},
    "space": {str(i): f"--sp-{i}" for i in range(1, 9)},
    "radius": {"small": "--radius-sm", "medium": "--radius", "pill": "--radius-pill"},
    "font_size": {"xs": "--fs-xs", "sm": "--fs-sm", "md": "--fs-md", "base": "--fs-base",
                  "lg": "--fs-lg", "xl": "--fs-xl", "xxl": "--fs-2xl", "display": "--fs-display"},
    "font_weight": {"normal": "--fw-normal", "medium": "--fw-medium",
                    "semibold": "--fw-semibold", "bold": "--fw-bold"},
    "duration": {"fast": "--dur-1", "medium": "--dur-2", "slow": "--dur-3"},
    "easing": {"out": "--ease-out", "spatial": "--ease-spatial"},
}


def _color(v: str) -> str:
    v = v.strip()
    if re.fullmatch(r"#[0-9a-fA-F]{6}", v):
        return v.upper()
    m = re.fullmatch(r"rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)", v)
    if m:
        r, g, b = (int(m.group(i)) for i in (1, 2, 3))
        a = round(float(m.group(4)) * 255)
        return f"#{r:02X}{g:02X}{b:02X}{a:02X}"
    raise ValueError(f"not a colour this generator understands: {v!r}")


def _px(v: str):
    v = v.strip()
    if v.endswith("px"):
        return float(v[:-2])
    if v.endswith("rem"):
        return round(float(v[:-3]) * 16, 2)
    m = re.fullmatch(r"clamp\(([^,]+),\s*([^,]+),\s*([^)]+)\)", v)
    if m:   # a fluid size: native gets its bounds
        return {"min": _px(m.group(1)), "max": _px(m.group(3))}
    raise ValueError(f"not a size: {v!r}")


def _ms(v: str) -> float:
    v = v.strip()
    return float(v[:-2]) if v.endswith("ms") else float(v[:-1]) * 1000


def _bezier(v: str) -> list[float]:
    m = re.fullmatch(r"cubic-bezier\(([^)]+)\)", v.strip())
    return [float(x) for x in m.group(1).split(",")]


CONVERT = {"color": _color, "state": _color, "space": _px, "radius": _px,
           "font_size": _px, "font_weight": lambda v: int(v), "duration": _ms,
           "easing": _bezier}


def tokens() -> dict:
    css = _gt.tokens((REPO / "frontend" / "index.html").read_text(encoding="utf-8"))
    out = {"$schema_version": 1,
           "$source": "frontend/index.html :root, via scripts/gen_design_tokens.py",
           "$units": "px at a 16px root (dp on Android, pt on Apple); ms; cubic-bezier; #RRGGBB[AA]"}
    for group, names in MAPPING.items():
        out[group] = {k: CONVERT[group](css[var]) for k, var in names.items()}
    return out


def _argb(hex_: str) -> str:
    h = hex_[1:]
    rgb, a = h[:6], (h[6:] or "FF")
    return f"0x{a}{rgb}"


def _camel(s: str) -> str:
    head, *rest = s.split("_")
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


HEADER = "Generated by scripts/gen_design_tokens.py from design/tokens.json. Do not edit."


def kotlin(t: dict) -> str:
    lines = [f"// {HEADER}", "package dev.wavr.core.nativeui", "",
             "import androidx.compose.ui.graphics.Color", "", "object WavrTokens {"]
    for k, v in t["color"].items():
        name = "background" if k == "background" else _camel(k)
        lines.append(f"    val {name} = Color({_argb(v)})")
    lines.append("    val dim = textDim")
    for k, v in t["state"].items():
        lines.append(f"    val {k} = Color({_argb(v)})")
    for k, v in t["space"].items():
        lines.append(f"    const val SPACE_{k} = {v}f")
    for k, v in t["radius"].items():
        lines.append(f"    const val RADIUS_{k.upper()} = {v}f")
    for k, v in t["font_size"].items():
        v = v["max"] if isinstance(v, dict) else v
        lines.append(f"    const val FONT_{k.upper()} = {v}f")
    for k, v in t["duration"].items():
        lines.append(f"    const val DURATION_{k.upper()}_MS = {int(v)}")
    lines += ["", "    /** The colour of a runtime state; anything unrecognised is \"unknown\". */",
              "    fun forState(state: String?): Color = when (state) {"]
    lines += [f'        "{s}" -> {s}' for s in STATES if s != "unknown"]
    lines += ["        else -> unknown", "    }", "}", ""]
    return "\n".join(lines)


def swift(t: dict) -> str:
    def col(h):
        r, g, b = (int(h[i:i + 2], 16) for i in (1, 3, 5))
        a = int(h[7:9], 16) / 255 if len(h) == 9 else 1
        return (f"Color(.sRGB, red: {r} / 255.0, green: {g} / 255.0, blue: {b} / 255.0, "
                f"opacity: {round(a, 4)})")
    # WavrState (the state enum colour(for:) takes) lives in WavrModels.
    lines = [f"// {HEADER}", "import SwiftUI", "import WavrModels", "", "public enum WavrTokens {"]
    for k, v in t["color"].items():
        lines.append(f"    public static let {_camel(k)} = {col(v)}")
    lines.append("    public static let dim = textDim")
    for k, v in t["state"].items():
        lines.append(f"    public static let {k} = {col(v)}")
    for k, v in t["space"].items():
        lines.append(f"    public static let space{k}: CGFloat = {v}")
    for k, v in t["font_size"].items():
        v = v["max"] if isinstance(v, dict) else v
        lines.append(f"    public static let font{k[:1].upper() + k[1:]}: CGFloat = {v}")
    lines += ["", "    /// The colour of a runtime state; unrecognised or missing is \"unknown\".",
              "    public static func color(for state: WavrState?) -> Color {",
              "        switch state {"]
    lines += [f"        case .{s}: return {s}" for s in STATES if s != "unknown"]
    lines += ["        case .unknown, .none: return unknown", "        }", "    }", "}", ""]
    return "\n".join(lines)


def rust(t: dict) -> str:
    lines = [f"// {HEADER}", ""]
    for k, v in t["color"].items():
        name = {"background": "BG"}.get(k, k.upper())
        lines.append(f'pub const {name}: &str = "{v}";')
    lines.append("pub const DIM: &str = TEXT_DIM;")
    for k, v in t["state"].items():
        lines.append(f'pub const {k.upper()}: &str = "{v}";')
    for k, v in t["space"].items():
        lines.append(f"pub const SPACE_{k}: f32 = {float(v)};")
    lines += ["", "/// The colour of a runtime state; unrecognised or missing is \"unknown\".",
              "pub fn state_color(state: Option<&str>) -> &'static str {", "    match state {"]
    lines += [f'        Some("{s}") => {s.upper()},' for s in STATES if s != "unknown"]
    lines += ["        _ => UNKNOWN,", "    }", "}", ""]
    return "\n".join(lines)


OUTPUTS = {
    REPO / "design" / "tokens.json": lambda t: json.dumps(t, indent=1) + "\n",
    REPO / "core-launcher/app/src/main/java/dev/wavr/core/nativeui/WavrTokens.kt": kotlin,
    REPO / "clients/apple/Sources/WavrKit/WavrTokens.swift": swift,
    REPO / "clients/desktop/src/theme.rs": rust,
}


def main(argv=None) -> int:
    check = "--check" in (argv if argv is not None else sys.argv[1:])
    t = tokens()
    stale = []
    for path, render in OUTPUTS.items():
        text = render(t)
        current = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else None
        if current != text:
            stale.append(str(path.relative_to(REPO)))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    if check and stale:
        print("stale design tokens (run scripts/gen_design_tokens.py): " + ", ".join(stale))
        return 1
    print("up to date" if not stale else "wrote " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
