"""DEV-TIME generator for an expanded offline OUI table (OPTIONAL).

Reads a locally downloaded copy of the PUBLIC IEEE MA-L registry CSV and
emits ``backend/wavr/data/oui_generated.py`` -- a compact
``OUI_VENDORS_GENERATED`` dict that ``wavr.data.oui.lookup_vendor`` uses as a
fallback after the curated table. This script is NEVER run at runtime and
Wavr NEVER fetches anything: download the CSV yourself, once, by hand:

    https://standards-oui.ieee.org/oui/oui.csv          (public IEEE data)

Usage (from the repo root):
    python scripts/gen_oui.py path/to/oui.csv [--keep "Apple,Sonos,..."]

Without --keep, a built-in keep-list of common home/IoT vendor name
substrings is used, so the emitted module stays a few thousand rows instead
of ~35k. The whole pipeline is stdlib-only.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

OUT_PATH = Path(__file__).resolve().parents[1] / "backend" / "wavr" / "data" / "oui_generated.py"

# Case-insensitive substrings matched against the IEEE "Organization Name"
# column. Deliberately home/IoT-centric -- this is a fallback table, not a
# mirror of the registry.
DEFAULT_KEEP = (
    "apple", "samsung", "google", "nest", "amazon", "ring", "xiaomi", "lumi",
    "espressif", "tuya", "raspberry", "tp-link", "tplink", "intel",
    "ubiquiti", "netgear", "linksys", "d-link", "sonos", "bose", "microsoft",
    "sony", "nintendo", "huawei", "hewlett", "brother", "canon", "epson",
    "dell", "lg elec", "lg inno", "lenovo", "asus", "nvidia", "roku",
    "hikvision", "dahua", "reolink", "wyze", "fitbit", "garmin", "oneplus",
    "motorola", "synology", "qnap", "western digital", "philips", "signify",
    "lifx", "belkin", "ecobee", "realtek", "honeywell", "logitech", "wemo",
    "arlo", "eufy", "anker", "shelly", "allterco", "aqara", "ikea",
)

_HEADER = '''"""AUTO-GENERATED by scripts/gen_oui.py from the public IEEE MA-L
registry CSV (standards-oui.ieee.org). Do not edit by hand; regenerate at dev
time instead. Optional: wavr.data.oui works fine when this file is absent.
"""
OUI_VENDORS_GENERATED: dict[str, str] = {
'''


def _norm_prefix(assignment: str) -> str | None:
    """IEEE 'Assignment' column ('A483E7') -> 'a4:83:e7'. None if malformed."""
    a = assignment.strip().lower()
    if len(a) != 6 or any(c not in "0123456789abcdef" for c in a):
        return None
    return f"{a[0:2]}:{a[2:4]}:{a[4:6]}"


def generate(csv_path: str, keep: tuple[str, ...]) -> dict[str, str]:
    table: dict[str, str] = {}
    with open(csv_path, newline="", encoding="utf-8", errors="replace") as fh:
        for row in csv.DictReader(fh):
            if row.get("Registry", "MA-L").strip() != "MA-L":
                continue
            org = (row.get("Organization Name") or "").strip()
            prefix = _norm_prefix(row.get("Assignment") or "")
            if not org or not prefix:
                continue
            low = org.lower()
            if any(k in low for k in keep):
                table[prefix] = org
    return table


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("csv", help="path to a locally downloaded IEEE oui.csv")
    ap.add_argument("--keep", default="",
                    help="comma-separated vendor-name substrings (overrides the default keep-list)")
    args = ap.parse_args()

    keep = tuple(k.strip().lower() for k in args.keep.split(",") if k.strip()) or DEFAULT_KEEP
    table = generate(args.csv, keep)
    if not table:
        print("no rows matched the keep-list; nothing written", file=sys.stderr)
        return 1

    lines = [_HEADER]
    for prefix in sorted(table):
        org = table[prefix].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{prefix}": "{org}",\n')
    lines.append("}\n")
    OUT_PATH.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {len(table)} prefixes -> {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
