// Generated by scripts/gen_design_tokens.py from design/tokens.json. Do not edit.

pub const BG: &str = "#0B0E12";
pub const STAGE: &str = "#070A0D";
pub const SURFACE: &str = "#141920";
pub const SURFACE_INSET: &str = "#10151B";
pub const ELEVATED: &str = "#1C232C";
pub const ELEVATED_2: &str = "#232B35";
pub const LINE: &str = "#FFFFFF12";
pub const LINE_STRONG: &str = "#FFFFFF21";
pub const TEXT: &str = "#EAECEE";
pub const TEXT_DIM: &str = "#9AA4AD";
pub const TEXT_FAINT: &str = "#7E8B95";
pub const ACCENT: &str = "#3DB54A";
pub const INFO: &str = "#62A6DA";
pub const WARN: &str = "#E8A13A";
pub const DANGER: &str = "#E8726A";
pub const ZONE: &str = "#6EA8FE";
pub const DIM: &str = TEXT_DIM;
pub const HEALTHY: &str = "#3DB54A";
pub const STARTING: &str = "#7E8B95";
pub const UPDATING: &str = "#62A6DA";
pub const PAUSED: &str = "#9AA4AD";
pub const DEGRADED: &str = "#E8A13A";
pub const ATTENTION: &str = "#E76423";
pub const UNAVAILABLE: &str = "#E8726A";
pub const UNKNOWN: &str = "#7E8B95";
pub const SPACE_1: f32 = 4.0;
pub const SPACE_2: f32 = 8.0;
pub const SPACE_3: f32 = 12.0;
pub const SPACE_4: f32 = 16.0;
pub const SPACE_5: f32 = 24.0;
pub const SPACE_6: f32 = 32.0;
pub const SPACE_7: f32 = 48.0;
pub const SPACE_8: f32 = 64.0;

/// The colour of a runtime state; unrecognised or missing is "unknown".
pub fn state_color(state: Option<&str>) -> &'static str {
    match state {
        Some("healthy") => HEALTHY,
        Some("starting") => STARTING,
        Some("updating") => UPDATING,
        Some("paused") => PAUSED,
        Some("degraded") => DEGRADED,
        Some("attention") => ATTENTION,
        Some("unavailable") => UNAVAILABLE,
        _ => UNKNOWN,
    }
}
