// Generated by scripts/gen_design_tokens.py from design/tokens.json. Do not edit.
import SwiftUI
import WavrModels

public enum WavrTokens {
    public static let background = Color(.sRGB, red: 11 / 255.0, green: 14 / 255.0, blue: 18 / 255.0, opacity: 1)
    public static let stage = Color(.sRGB, red: 7 / 255.0, green: 10 / 255.0, blue: 13 / 255.0, opacity: 1)
    public static let surface = Color(.sRGB, red: 20 / 255.0, green: 25 / 255.0, blue: 32 / 255.0, opacity: 1)
    public static let surfaceInset = Color(.sRGB, red: 16 / 255.0, green: 21 / 255.0, blue: 27 / 255.0, opacity: 1)
    public static let elevated = Color(.sRGB, red: 28 / 255.0, green: 35 / 255.0, blue: 44 / 255.0, opacity: 1)
    public static let elevated2 = Color(.sRGB, red: 35 / 255.0, green: 43 / 255.0, blue: 53 / 255.0, opacity: 1)
    public static let line = Color(.sRGB, red: 255 / 255.0, green: 255 / 255.0, blue: 255 / 255.0, opacity: 0.0706)
    public static let lineStrong = Color(.sRGB, red: 255 / 255.0, green: 255 / 255.0, blue: 255 / 255.0, opacity: 0.1294)
    public static let text = Color(.sRGB, red: 234 / 255.0, green: 236 / 255.0, blue: 238 / 255.0, opacity: 1)
    public static let textDim = Color(.sRGB, red: 154 / 255.0, green: 164 / 255.0, blue: 173 / 255.0, opacity: 1)
    public static let textFaint = Color(.sRGB, red: 126 / 255.0, green: 139 / 255.0, blue: 149 / 255.0, opacity: 1)
    public static let accent = Color(.sRGB, red: 61 / 255.0, green: 181 / 255.0, blue: 74 / 255.0, opacity: 1)
    public static let info = Color(.sRGB, red: 98 / 255.0, green: 166 / 255.0, blue: 218 / 255.0, opacity: 1)
    public static let warn = Color(.sRGB, red: 232 / 255.0, green: 161 / 255.0, blue: 58 / 255.0, opacity: 1)
    public static let danger = Color(.sRGB, red: 232 / 255.0, green: 114 / 255.0, blue: 106 / 255.0, opacity: 1)
    public static let zone = Color(.sRGB, red: 110 / 255.0, green: 168 / 255.0, blue: 254 / 255.0, opacity: 1)
    public static let dim = textDim
    public static let healthy = Color(.sRGB, red: 61 / 255.0, green: 181 / 255.0, blue: 74 / 255.0, opacity: 1)
    public static let starting = Color(.sRGB, red: 126 / 255.0, green: 139 / 255.0, blue: 149 / 255.0, opacity: 1)
    public static let updating = Color(.sRGB, red: 98 / 255.0, green: 166 / 255.0, blue: 218 / 255.0, opacity: 1)
    public static let paused = Color(.sRGB, red: 154 / 255.0, green: 164 / 255.0, blue: 173 / 255.0, opacity: 1)
    public static let degraded = Color(.sRGB, red: 232 / 255.0, green: 161 / 255.0, blue: 58 / 255.0, opacity: 1)
    public static let attention = Color(.sRGB, red: 231 / 255.0, green: 100 / 255.0, blue: 35 / 255.0, opacity: 1)
    public static let unavailable = Color(.sRGB, red: 232 / 255.0, green: 114 / 255.0, blue: 106 / 255.0, opacity: 1)
    public static let unknown = Color(.sRGB, red: 126 / 255.0, green: 139 / 255.0, blue: 149 / 255.0, opacity: 1)
    public static let space1: CGFloat = 4.0
    public static let space2: CGFloat = 8.0
    public static let space3: CGFloat = 12.0
    public static let space4: CGFloat = 16.0
    public static let space5: CGFloat = 24.0
    public static let space6: CGFloat = 32.0
    public static let space7: CGFloat = 48.0
    public static let space8: CGFloat = 64.0
    public static let fontXs: CGFloat = 11.52
    public static let fontSm: CGFloat = 12.48
    public static let fontMd: CGFloat = 13.12
    public static let fontBase: CGFloat = 14.4
    public static let fontLg: CGFloat = 16.0
    public static let fontXl: CGFloat = 17.6
    public static let fontXxl: CGFloat = 20.0
    public static let fontDisplay: CGFloat = 40.0

    /// The colour of a runtime state; unrecognised or missing is "unknown".
    public static func color(for state: WavrState?) -> Color {
        switch state {
        case .healthy: return healthy
        case .starting: return starting
        case .updating: return updating
        case .paused: return paused
        case .degraded: return degraded
        case .attention: return attention
        case .unavailable: return unavailable
        case .unknown, .none: return unknown
        }
    }
}
